# Generated by Django 4.2.19 on 2025-04-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_client_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale', verbose_name='sales'),
        ),
    ]
