# Generated by Django 4.2.19 on 2025-04-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_detail_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.sale', verbose_name='Venta'),
        ),
    ]
