# Generated by Django 4.2.19 on 2025-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_detail_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pago'),
        ),
    ]
