# Generated by Django 4.2.20 on 2025-04-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_change_sale_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
