# Generated by Django 4.2.19 on 2025-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
