# Generated by Django 4.2.19 on 2025-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_whatsapp_suppliercontact_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido'),
        ),
    ]
