# Generated by Django 4.2.19 on 2025-02-19 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_suppliercontact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercontact',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Apellido'),
            preserve_default=False,
        ),
    ]
